// <auto-generated />
namespace Jeopardy.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class addedCategoryIdToQuestionModels : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedCategoryIdToQuestionModels));
        
        string IMigrationMetadata.Id
        {
            get { return "201508162210423_addedCategoryIdToQuestionModels"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
